name: Google Play Console Prod

on:
  release:
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Installing Node version 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
    
      - name: Installing Dependencies
        run: npm install

      - name: Change wrapper permissions
        working-directory: ./android
        run: chmod +x ./gradlew

      - name: Run Tests
        working-directory: ./android
        run: ./gradlew test

      - name: Build Project
        working-directory: ./android
        run: ./gradlew assemble


  publish:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Installing Node version 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
    
      - name: Installing Dependencies
        run: npm install

      - name: Change wrapper permissions
        working-directory: ./android
        run: chmod +x ./gradlew

      - name: Run Tests
        working-directory: ./android
        run: ./gradlew test

      - name: Assemble Project
        working-directory: ./android
        run: ./gradlew assembleRelease

      - name: Build Project
        working-directory: ./android
        run: ./gradlew buildRelease

      - name: Build Release AAB
        working-directory: ./android
        run: ./gradlew bundleRelease

      - name: Deploy to Play Store
        uses: r0adkll/upload-google-play@v1.0.15
        with:
          serviceAccountJsonPlainText: ${{secrets.SERVICE_ACCOUNT}}
          packageName: com.StudyBox
          releaseFiles: android/app/build/outputs/bundle/release/app-release.aab
          track: production
