name: Gradle Android Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Installing Node version 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Define API URL
        run: echo API_URL=https://dev.api.studybox.fr > .env

      - name: Installing Dependencies
        run: npm install

      - name: Change wrapper permissions
        working-directory: ./android
        run: chmod +x ./gradlew

      - name: Run Tests
        working-directory: ./android
        run: ./gradlew test

      - name: Build Project
        working-directory: ./android
        run: ./gradlew assembleRelease

      - name: Saving Debug Apk as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: StudyBox-Dev-Apk
          retention-days: 7
          path: android/app/build/outputs/apk/release/app-release.apk
