name: Gradle Android Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./StudyBox

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Installing Node version 14
        uses: actions/setup-node@v2
        with:
          node-version: 16
    
      - name: Installing Dependencies
        run: npm install

      - name: Change wrapper permissions
        working-directory: ./StudyBox/android
        run: chmod +x ./gradlew

      - name: Run Tests
        working-directory: ./StudyBox/android
        run: ./gradlew test

      - name: Build Project
        working-directory: ./StudyBox/android
        run: ./gradlew assemble
