name: Project Linter

on:
  push:
    branches: ['!master', '!develop']
  pull_request:

jobs:
  lint:
    name: ESLint Linter
    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: ./StudyBox

    steps:
      - name: Retrieving Latest Code
        uses: actions/checkout@v2

      - name: Installing Node version 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Installing Dependencies
        run: npm install

      - name: Executing Linter Scan
        run: npm run lint
