name: Testing Policy

on:
  push:
  pull_request:
  release:

jobs:
  tests:
    name: Jest Testing Policy
    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: ./StudyBox

    steps:
      - name: Retrieving Latest Code
        uses: actions/checkout@v2

      - name: Installing Node version 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Installing Dependencies
        run: npm install

      - name: Executing Jest Tests
        run: npm run test
