name: Testing Policy

on:
  push:
  pull_request:

jobs:
  tests:
    name: Jest Testing Policy
    runs-on: ubuntu-20.04

    steps:
      - name: Retrieving Latest Code
        uses: actions/checkout@v3

      - name: Installing Node version 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Installing Dependencies
        run: npm install

      - name: Executing Jest Tests
        run: npm run test
